### ISSUE TITLE
[Documentation] main.py

### ISSUE THREAD

**Issue by rubyFeedback** [pawptart/raytrace-ruby#2]
Heya there, I think a small typo in the README:

    Clone this repository, then:

    ruby main.py

I think there is no main.py; main.rb was meant (I think).

Anyway, great screenshots! The comparison makes this fun
aka "good" versus "noob" rendering. ;-)

**Comment by ty-porter** [comment]
Thanks, yeah, I did make a typo there. It's been corrected.
